apiVersion: apps/v1
kind: Deployment
metadata:
  name: way-io
spec:
  selector:
    matchLabels:
      app: way-io
  template:
    metadata:
      labels:
        app: way-io
    spec:
      containers:
      - name: way-io
        image: zeussh/way-io:1
        ports:
        - containerPort: 8084
        env:
        - name: EUREKA_HOST
          value: "http://way-discovery:8761/eureka"
        - name: JDBC_DATABASE_URL
          value: "jdbc:postgresql://postgres:5432/wayconsig"
        - name: JDBC_DATABASE_USERNAME
          value: "postrgres"
        - name: JDBC_DATABASE_PASSWORD
          value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: way-io
spec:
  selector:
    app: way-io
  ports:
  - port: 8084
    targetPort: 8084
    protocol: TCP
