# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: way-web
# spec:
#   selector:
#     matchLabels:
#       app: way-web
#   template:
#     metadata:
#       labels:
#         app: way-web
#     spec:
#       containers:
#       - name: way-web
#         image: zeussh/way-web:1
#         ports:
#         - containerPort: 8761
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: way-web
# spec:
#   selector:
#     app: way-web
#   ports:
#   - port: 8761
#     targetPort: 8761
#     protocol: TCP
